-- -----------------------------------------------------
-- Schema book-shop-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `book-shop-ecommerce`;

CREATE SCHEMA `book-shop-ecommerce`;
USE `book-shop-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-shop-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `book-shop-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book-shop-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Books');
INSERT INTO product_category(category_name) VALUES ('Coffee Mugs');
INSERT INTO product_category(category_name) VALUES ('Key Chain');
INSERT INTO product_category(category_name) VALUES ('Mouse Pads');
-- -----------------------------------------------------
-- Books
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1000', 'First Civilizations', 'The history of first civilizations from 8,000 b.c until Christ birth.', 'assets/images/products/books/book-elisa-1000.png', 1, 100, 20.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1001', 'The History of Vicking', 'The history of first civilization from Scandinavia.', 'assets/images/products/books/book-elisa-1001.png', 1, 100, 25.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1002', 'The Huns', 'The history of powerful civilization from past Mongolia.', 'assets/images/products/books/book-elisa-1002.png', 1, 100, 19.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1003', 'The Ancient Egipt', 'Discover the history of this facinating civilization.', 'assets/images/products/books/book-elisa-1003.png', 1, 100, 14.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1004', 'The Roman Empire ', 'Discover the history of this great empire - The rise and the fall', 'assets/images/products/books/book-elisa-1004.png', 1, 100, 20.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1005', 'Middle Age', 'A 1000 years of history.', 'assets/images/products/books/book-elisa-1005.png', 1, 100, 21.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1006', 'The Renaissance ', 'Learn the period of rebirth after 1000 years of middle age.', 'assets/images/products/books/book-elisa-1006.png', 1, 100, 24.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1007', 'French Revolution', 'Learn what caused and everything you need to know about French Revolution.', 'assets/images/products/books/book-elisa-1007.png', 1, 100, 23.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1008', 'The History of the Greeks', 'Learn everything about The History of the Greeks.', 'assets/images/products/books/book-elisa-1008.png', 1, 100, 21.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1009', 'The History of England', 'Learn everything about The History of England.', 'assets/images/products/books/book-elisa-1009.png', 1, 100, 25.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1010', 'The History of France', 'Learn everything about The History of France.', 'assets/images/products/books/book-elisa-1010.png', 1, 100, 16.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1011', 'The History of Italy', 'Learn everything about The History of Italy.', 'assets/images/products/books/book-elisa-1011.png', 1, 100, 27.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1012', 'The History of Portugal', 'Learn everything about The History of Portugal.', 'assets/images/products/books/book-elisa-1012.png', 1, 100, 20.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1013', 'The History of Spain', 'Learn everything about The History of Spain.', 'assets/images/products/books/book-elisa-1013.png', 1, 100, 14.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1014', 'The History of Russia', 'Learn everything about The History of Russia.', 'assets/images/products/books/book-elisa-1014.png', 1, 100, 17.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1015', 'The History of China', 'Learn everything about The History of China.', 'assets/images/products/books/book-elisa-1015.png', 1, 100, 20.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1016', 'The History of Japan', 'Learn everything about The History of Japan.', 'assets/images/products/books/book-elisa-1016.png', 1, 100, 21.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1017', 'The History of Brazil', 'Learn everything about The History of Brazil.', 'assets/images/products/books/book-elisa-1017.png', 1, 100, 24.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1018', 'The History of Canada', 'Learn everything about The History of Canada.', 'assets/images/products/books/book-elisa-1018.png', 1, 100, 23.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1019', 'The History of United States ', 'Learn everything about The History of United States .', 'assets/images/products/books/book-elisa-1019.png', 1, 100, 21.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1020', 'The History of Mexico', 'Learn everything about The History of Mexico.', 'assets/images/products/books/book-elisa-1020.png', 1, 100, 25.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1021', 'The History of Chile', 'Learn everything about The History of Chile.', 'assets/images/products/books/book-elisa-1021.png', 1, 100, 25.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1022', 'New Geopolitics', 'Learn everything about New Geopolitics.', 'assets/images/products/books/book-elisa-1022.png', 1, 100, 19.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1023', 'The Cold War', 'Learn everything about The Cold War.', 'assets/images/products/books/book-elisa-1023.png', 1, 100, 14.99, 1, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('BOOK-HIST-1024', 'Beautiful Africa', 'Learn everything about Beautiful Africa.', 'assets/images/products/books/book-elisa-1024.png', 1, 100, 20.99, 1, Now());



-- -----------------------------------------------------
-- Coffee Mugs
-- -----------------------------------------------------

INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1000', 'Coffee Mug -Los Muertos (Black)', 'Are your facinated about Mexico ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1000.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1001', 'Coffee Mug -Los Muertos (White)', 'Are your facinated about Mexico ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1001.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1002', 'Coffee Mug -Vickings (White)', 'Are your facinated about Vickings ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1002.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1003', 'Coffee Mug -Vickings (Black)', 'Are your facinated about Vickings ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1003.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1004', 'Coffee Mug -Canada (White)', 'Are your facinated about Canada ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1004.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1005', 'Coffee Mug -Canada (Black)', 'Are your facinated about Canada ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1005.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1006', 'Coffee Mug -France', 'Are your facinated about France ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1006.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1007', 'Coffee Mug -England', 'Are your facinated about England ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1007.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1008', 'Coffee Mug -Ireland', 'Are your facinated about Ireland ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1008.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1009', 'Coffee Mug -Egipt', 'Are your facinated about Egipt ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1009.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1010', 'Coffee Mug -Sloth', 'Are your facinated about Sloths ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1010.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1011', 'Coffee Mug -United States', 'Are your facinated about United States ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1011.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1012', 'Coffee Mug -Greece', 'Are your facinated about Greece ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1012.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1013', 'Coffee Mug -Portugal', 'Are your facinated about Portugal ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1013.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1014', 'Coffee Mug -Spain', 'Are your facinated about Spain ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1014.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1015', 'Coffee Mug -Italy', 'Are your facinated about Italy ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1015.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1016', 'Coffee Mug -Russia', 'Are your facinated about Russia ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1016.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1017', 'Coffee Mug -China', 'Are your facinated about China ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1017.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1018', 'Coffee Mug -Japan', 'Are your facinated about Japan ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1018.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1019', 'Coffee Mug -Africa black', 'Are your facinated about Africa ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1019.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1020', 'Coffee Mug -Africa white', 'Are your facinated about Africa ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1020.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1021', 'Coffee Mug -Alpaca', 'Are your facinated about Alpacas ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1021.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1022', 'Coffee Mug -Meditation', 'Are your facinated about Meditation ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1022.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1023', 'Coffee Mug -Cherrie Blossom', 'Are your facinated about Cherrie Blossom ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1023.png', 1, 100, 16.99, 2, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('COFFEEMUG-1024', 'Coffee Mug -Ganesha', 'Are your facinated about Ganesha ? Then you must have this gorgeous coffee mug.', 'assets/images/products/coffeemugs/coffemug-elisa-1024.png', 1, 100, 16.99, 2, Now());



-- -----------------------------------------------------
-- Key Chain
-- -----------------------------------------------------

INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1000', 'Key Chain - Frida Kahlo', 'Do you like Frida Kahlo ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1000.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1001', 'Key Chain - Los Muertos', 'Do you like Mexico ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1001.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1002', 'Key Chain - Vickings Black I', 'Do you like Vickings ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1002.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1003', 'Key Chain - Vickings Black II', 'Do you like Vickings ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1003.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1004', 'Key Chain - Canada Black', 'Do you like Canada ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1004.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1005', 'Key Chain - Canada white', 'Do you like Canada ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1005.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1006', 'Key Chain - Egipt', 'Do you like Egipt ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1006.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1007', 'Key Chain - Unites Stated', 'Do you like Unites Stated ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1007.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1008', 'Key Chain - China', 'Do you like China ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1008.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1009', 'Key Chain - Japan', 'Do you like Japan ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1009.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1010', 'Key Chain - France', 'Do you like France ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1010.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1011', 'Key Chain - England', 'Do you like England ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1011.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1012', 'Key Chain - India', 'Do you like India ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1012.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1013', 'Key Chain - Brazil', 'Do you like Brazil ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1013.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1014', 'Key Chain - Portugal', 'Do you like Portugal ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1014.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1015', 'Key Chain - Spain', 'Do you like Spain ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1015.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1016', 'Key Chain - Italy', 'Do you like Italy ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1016.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1017', 'Key Chain - Russia', 'Do you like Russia ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1017.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1018', 'Key Chain - Peru', 'Do you like Peru ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1018.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1019', 'Key Chain - Olpaca', 'Do you like Olpaca ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1019.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1020', 'Key Chain - Meditation', 'Do you like Meditation ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1020.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1021', 'Key Chain - Ganesha', 'Do you like Ganesha ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1021.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1022', 'Key Chain - Africa I', 'Do you like Africa ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1022.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1023', 'Key Chain - Africa II', 'Do you like Africa ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1023.png', 1, 100, 8.99, 3, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('KEYCHAIN-1024', 'Key Chain - Africa III', 'Do you like Africa ? Then you must have this cute keychain', 'assets/images/products/keychain/keychain-elisa-1024.png', 1, 100, 8.99, 3, Now());



-- -----------------------------------------------------
-- Mouse Pads
-- -----------------------------------------------------

INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1000', 'Mouse Pad - Vicking', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1000.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1001', 'Mouse Pad - Canada', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1001.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1002', 'Mouse Pad - France', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1002.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1003', 'Mouse Pad - England', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1003.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1004', 'Mouse Pad - Ireland', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1004.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1005', 'Mouse Pad - Egipt', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1005.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1006', 'Mouse Pad - Frida Kahlo', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1006.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1007', 'Mouse Pad - Brazil', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1007.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1008', 'Mouse Pad - USA', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1008.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1009', 'Mouse Pad - Greece', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1009.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1010', 'Mouse Pad - Italy', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1010.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1011', 'Mouse Pad - Portugal', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1011.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1012', 'Mouse Pad - Germany', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1012.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1013', 'Mouse Pad - Spain', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1013.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1014', 'Mouse Pad - Sloth', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1014.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1015', 'Mouse Pad - China', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1015.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1016', 'Mouse Pad - Japan', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1016.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1017', 'Mouse Pad - Australia', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1017.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1018', 'Mouse Pad - Africa', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1018.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1019', 'Mouse Pad - Olpaca ', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1019.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1020', 'Mouse Pad - Olpaca ', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1020.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1021', 'Mouse Pad - Ganesha', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1021.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1022', 'Mouse Pad - Sloth happy', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1022.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1023', 'Mouse Pad - Meditation', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1023.png', 1, 100, 17.99, 4, Now());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES('MOUSEPAD-1024', 'Mouse Pad - Life tree', 'The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-elisa-1024.png', 1, 100, 17.99, 4, Now());

